<?php
    $this->headScript()->appendFile($this->baseUrl.'/js/vendor/extjs/build/ext-all-debug.js');
    $this->headScript()->appendFile($this->baseUrl.'/js/ClientsModule.js');
    $this->headLink()->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', 'screen');
    //$this->headLink()->appendStylesheet($this->baseUrl.'/css/Clients.css', 'screen'); 
    //$this->headLink()->appendStylesheet($this->baseUrl.'/css/app.css', 'screen');
    $this->headLink()->appendStylesheet($this->baseUrl.'/js/vendor/extjs/resources/styles/MyApp-all.css', 'screen');
?>
<div id="binding-example">
</div>